# kill EVERYTHING except errors
org.slf4j.simpleLogger.defaultLogLevel=error

# kill kafka specifically
org.slf4j.simpleLogger.log.org.apache.kafka=error

# optional
org.slf4j.simpleLogger.log.org.apache=error

# clean output
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false
org.slf4j.simpleLogger.showShortLogName=false